language: php
php:
  - "7.3"

services:
  - docker

before_install:
- docker ps -a
- docker-compose build
- docker ps -a

notifications:
  email:
    - jocastelblanco3@poligran.edu.co
    - huangulo@poligran.edu.co

script: 
  - phpunit www/test.php