language: php
php:
  - "7.3"

services:
  - docker

before_install:
- docker ps -a
- docker-compose build
- docker ps -a
- curl -s http://getcomposer.org/installer | php
- php composer.phar install

script: phpunit

notifications:
  email:
    - jocastelblanco3@poligran.edu.co
    - huangulo@poligran.edu.co